person:
  hydrate: "currentTeam,team,stats(type=[yearByYear,yearByYearAdvanced,careerRegularSeason,careerAdvanced,availableStats](team(league)),leagueListId=mlb_hist)"

boxes:
  - kind: basic
    side: back
    description: Name and Position Code over Team Name
    values:
      - script: .fullName + ",  " + .primaryPosition.abbreviation
        value: person
      - script: .currentTeam.name
        value: person
  - kind: basic
    side: back
    description: Born, Height, Weight and Sided-ness
    values:
      - name: Born
        script: (.birthDate | strptime("%Y-%m-%d") | strftime("%-m/%-d/%y")) + ",  " + .birthCity + ",  " + .birthStateProvince
        value: person
      - name: Ht
        script: .height
        value: person
      - name: Wt
        script: .weight
        value: person
      - name: Bats
        script: .batSide.code
        value: person
      - name: Throws
        script: .pitchHand.code
        value: person
  - kind: frame
    side: back
    description: Yearly career stats
    values:
      - name: YEAR
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .season | tonumber ]'
        value: person
      - name: TEAM
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .team.teamName ]'
        value: person
      - name: W
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.wins ]'
        value: person
      - name: L
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.losses ]'
        value: person
      - name: PCT
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.winPercentage | tonumber ]'
        value: person
      - name: G
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.gamesPlayed ]'
        value: person
      - name: GS
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.gamesStarted ]'
        value: person
      - name: GG
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.completeGames ]'
        value: person
      - name: SHO
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.shutouts ]'
        value: person
      - name: SV
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.saves ]'
        value: person
      - name: IP
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.inningsPitched | tonumber ]'
        value: person
      - name: H
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.hits ]'
        value: person
      - name: BB
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.baseOnBalls ]'
        value: person
      - name: SO
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.strikeOuts ]'
        value: person
      - name: ERA
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.era | tonumber ]'
        value: person
      - name: BAA
        script: '[ .stats[] | select(.type.displayName == "yearByYear") | .splits[] | .stat.hits / (.stat.battersFaced - .stat.baseOnBalls) | tostring | .[:5] | tonumber ]'
        value: person

# todo: season totals


#images: